name: 'Code quality'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
      - run: |
          yarn run test
