name: 'Test the action'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: test
        with:
          branch-name: ${GITHUB_HEAD_REF}
      - run: echo ${{ steps.test.outputs.hashedBranchName }}
      - uses: ./
        id: test2
        with:
          branch-name: ${GITHUB_HEAD_REF}
          encoding: 'base64'
          output-length: 16
      - run: echo ${{ steps.test2.outputs.hashedBranchName }}
      - uses: ./
        id: test3
        with:
          branch-name: ${GITHUB_HEAD_REF}
          output-length: 12
          uppercase: false
      - run: echo ${{ steps.test3.outputs.hashedBranchName }}
      - uses: ./
        id: test4
        with:
          branch-name: ${GITHUB_HEAD_REF}
          output-length: 12
          uppercase: true
      - run: echo ${{ steps.test4.outputs.hashedBranchName }}
