name: 'Test the action'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: test
        with:
          branch-name: ${GITHUB_HEAD_REF} || ${GITHUB_REF} || ${GITHUB_REF_NAME}
      - run: echo ${{ steps.test.outputs.hashedBranchName }}
